""" Object to store position data generated by a DNN object detector.
    * Stores the bounding box, label, confidence, a timestamp of when
    the object was found, and a color to draw the object.
    * The class countains a method to draw the object on the image where
    it was detected.
"""

# ================ Third Party Imports ================ #

import cv2 as cv2

# ================ Authorship ================ #

__author__ = "Donald Max Harkins"
__contributors__ = ["Donald Max Harkins"]

# ================ Class defenition ================ #

class objData():
    def __init__(self, rect, timestamp, label, confidence, color):
        self.rect = rect
        self.timestamp = timestamp
        self.label = label
        self.confidence = confidence
        self.color = color

    def drawData(self, img):
         #draw a coloured rectangle around object.
         # rectangle did not play nice with numpy array, hence manual casting
         # Draw some text too
         (startX, startY, endX, endY) = self.rect
         text = "{} | {:.4f} | {}".format(self.label, self.confidence, self.timestamp)
         cv2.putText(img, text, (startX, startY - 5),
             cv2.FONT_HERSHEY_SIMPLEX, 0.5, self.color, 2)
         cv2.rectangle(img, (startX, startY), (endX, endY), self.color, thickness=2)
